version: '3'
services:
  mirror-scripts:
    image: minhhung123/mirror-scripts
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    ports:
      - 8000:8000